# Site settings
title: My Terraform Docs
description: A collection of Terraform documentation

# Theme settings
theme: minimal-mistakes-jekyll

# Build settings
markdown: kramdown
input: GFM
output: HTML
