# Site settings
title: My Terraform Docs
description: A collection of Terraform documentation

# Theme settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme 

# Build settings
markdown: kramdown
input: GFM
output: HTML
