markdown: 
  input: GFM
  output: HTML
title: My Terraform Commands
description: A dashboard for all Terraform command documentation
plugins:
  - jekyll-sitemap
  - jekyll-github-metadata
markdown: kramdown
permalink: /:categories/:title/
collections:
  terraform:
    output: true
    sort_by: title
defaults:
  - scope:
      path: ""
      type: "terraform"
    values:
      layout: "post"
      categories: ["terraform"]
