# Site settings
title: My Terraform Docs
description: A collection of Terraform documentation

# Theme settings
theme: jekyll-theme-so-simple

# Build settings
markdown: kramdown
input: GFM
output: HTML