markdown: 
  input: GFM
  output: HTML

theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "directories"
    values:
      layout: "directory"

# Home page
# This is the main page of your site and should be saved as index.md or index.html in the root directory
# You can customize this page by editing index.md
# This page will link to the various .md files in your tree
# Replace `my-site` with the name of your site
# Replace `My Site` with the title of your site
# Replace `commands` with the name of the first directory in your tree
# Replace `Commands` with the title of the first directory in your tree
# Repeat the `nav:` block for each directory and .md file in your tree
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "home"
      title: "My Site"
      nav:
        - text: "Commands"
          link: "/commands/"
        - text: "Files"
          link: "/files/"
        - text: "Language"
          link: "/language/"
        - text: "Overview"
          link: "/overview/"
        - text: "Registry"
          link: "/registry/"
        - text: "Terraform Cloud"
          link: "/terraform-cloud/"
        - text: "Terraform Enterprise"
          link: "/terraform-enterprise/"
  - scope:
      path: "commands"
      type: "directories"
    values:
      layout: "directory"
  - scope:
      path: "language"
      type: "directories"
    values:
      layout: "directory"

# Navigation links
# These are the links that appear at the top of your site
# Replace `my-site` with the name of your site
# Replace `My Site` with the title of your site
# Replace `commands` with the name of the first directory in your tree
# Replace `Commands` with the title of the first directory in your tree
# Repeat the `nav:` block for each directory and .md file in your tree
nav:
  - text: "Commands"
    link: "/commands/"
  - text: "Files"
    link: "/files/"
  - text: "Language"
    link: "/language/"
  - text: "Overview"
    link: "/overview/"
  - text: "Registry"
    link: "/registry/"
  - text: "Terraform Cloud"
    link: "/terraform-cloud/"
  - text: "Terraform Enterprise"
    link: "/terraform-enterprise/"
